import { Inter } from 'next/font/google';

import type { ReactNode } from 'react';

import '../styles/globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin', 'latin-ext'],
});

type RootLayoutProps = {
	children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang="en" className={inter.variable}>
			<body>
				<div className="min-w-screen min-h-screen bg-purple-dark tracking-wide">
					{children}
				</div>
			</body>
		</html>
	);
}
