export const Homepage = () => {
	return (
		<div>
			Witaj na stronie głównej
			{/* <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id quasi dolore commodi nobis odio? Non praesentium, ut explicabo aperiam nemo provident? Repudiandae expedita porro dignissimos neque nulla facilis non reiciendis!</p> */}
		</div>
	);
};
