"""Auth0 user info"""
type AuthInfo {
  sub: String
}

"""
A date string, such as 2007-12-03, compliant with the `full-date` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
"""
scalar Date

"""
A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
"""
scalar DateTime

scalar File

type Query {
  allUsers: [User!]!

  """Auth0 context info"""
  authInfo: AuthInfo
}

type Task {
  description: String!
  id: ID!
  title: String!
}

type User {
  email: String!
  id: ID!
  name: String!
  postedTasks: [Task!]!
}